"""initial schema: installs, byo_keys, csv_statements, conversations, turns, usage_events

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-09-05

Hand-written, not autogenerated, so every column/type/constraint below is a
deliberate choice matching the approved architecture design's schema exactly
(installs/usage_events/conversations/turns/byo_keys verbatim from the design
doc's SS2.4/SS3.1/SS4; csv_statements is this session's proposed elaboration
of the design doc's SS1 -- see the session-1 plan for the reasoning behind
every csv_statements column).

installs.byo_key_id and byo_keys.install_id are a circular foreign-key pair:
each table references the other. Sequenced as create installs (byo_key_id
column present but unconstrained) -> create byo_keys (its FK to installs is
fine, installs already exists) -> ALTER TABLE installs to add the deferred FK
-- the standard two-step pattern for a circular FK, rather than any special
Postgres-side trick.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial_schema"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_install_identity_type = sa.Enum("google_email", "uuid", name="install_identity_type")
_usage_event_outcome = sa.Enum(
    "answered",
    "hit_iteration_cap",
    "error",
    "rejected_free_window",
    "rejected_daily_cap",
    name="usage_event_outcome",
)
_csv_statement_status = sa.Enum("unconfirmed", "confirmed", name="csv_statement_status")

# Each enum above is used by exactly one table's column below (identity_type only in
# installs, status only in csv_statements, outcome only in usage_events). op.create_table's
# own column DDL creates each type automatically as part of that table's creation
# (checkfirst=False, unconditional) -- a separate explicit CREATE TYPE step beforehand was
# tried and found to collide with it ("already exists"), so upgrade() below relies on that
# automatic creation alone. This is NOT symmetric with dropping, though (confirmed live,
# not assumed): op.drop_table does *not* automatically drop the enum type the way
# op.create_table creates it, so downgrade() below still needs its own explicit .drop()
# calls -- omitting them (as an earlier version of this migration mistakenly did) leaves
# the types orphaned after the tables are dropped, which then collides with the *next*
# upgrade's automatic CREATE TYPE exactly like the case this comment opens with.


def upgrade() -> None:
    # 1. installs -- byo_key_id present, unconstrained until byo_keys exists (step 3 below).
    op.create_table(
        "installs",
        sa.Column("install_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("identity_type", _install_identity_type, nullable=False),
        sa.Column("identity_value", sa.Text(), nullable=False),
        sa.Column("free_window_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("byo_key_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_unique_constraint(
        "uq_installs_identity", "installs", ["identity_type", "identity_value"]
    )

    # 2. byo_keys -- FK to installs.install_id is fine now.
    op.create_table(
        "byo_keys",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "install_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("installs.install_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("encrypted_key", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
    )

    # 3. Deferred FK completing the circular pair.
    op.create_foreign_key(
        "fk_installs_byo_key_id", "installs", "byo_keys", ["byo_key_id"], ["id"]
    )

    # 4. csv_statements -- FK to installs.install_id.
    op.create_table(
        "csv_statements",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "install_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("installs.install_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "status", _csv_statement_status, nullable=False, server_default=sa.text("'unconfirmed'")
        ),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_columns", postgresql.JSONB(), nullable=True),
        sa.Column("proposed_mapping", postgresql.JSONB(), nullable=True),
        sa.Column("confirmed_mapping", postgresql.JSONB(), nullable=True),
        sa.Column("entity_name", sa.Text(), nullable=True),
        sa.Column("cadence", sa.Text(), nullable=True),
        sa.Column("statement_data", postgresql.JSONB(), nullable=True),
        sa.Column("statement_attrs", postgresql.JSONB(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
    )

    # 5. conversations -- FKs to installs.install_id, csv_statements.id.
    op.create_table(
        "conversations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "install_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("installs.install_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column(
            "csv_context_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("csv_statements.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
        sa.Column("last_turn_at", sa.DateTime(timezone=True), nullable=False),
    )

    # 6. turns -- FK to conversations.id.
    op.create_table(
        "turns",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "conversation_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("conversations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("final_answer", sa.Text(), nullable=False),
        sa.Column("hit_iteration_cap", sa.Boolean(), nullable=False),
        sa.Column("iterations_used", sa.Integer(), nullable=False),
        sa.Column("stop_reason", sa.Text(), nullable=True),
        sa.Column("figure_check", postgresql.JSONB(), nullable=False),
        sa.Column("tool_calls", postgresql.JSONB(), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
        ),
    )

    # 7. usage_events -- FKs to installs.install_id, turns.id, plus its composite index.
    op.create_table(
        "usage_events",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "install_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("installs.install_id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "turn_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("turns.id"), nullable=True
        ),
        sa.Column("outcome", _usage_event_outcome, nullable=False),
    )
    op.create_index(
        "ix_usage_events_install_id_occurred_at", "usage_events", ["install_id", "occurred_at"]
    )


def downgrade() -> None:
    bind = op.get_bind()

    op.drop_index("ix_usage_events_install_id_occurred_at", table_name="usage_events")
    op.drop_table("usage_events")
    op.drop_table("turns")
    op.drop_table("conversations")
    op.drop_table("csv_statements")
    op.drop_constraint("fk_installs_byo_key_id", "installs", type_="foreignkey")
    op.drop_table("byo_keys")
    op.drop_constraint("uq_installs_identity", "installs", type_="unique")
    op.drop_table("installs")

    # Dropping the tables above does NOT drop these types (see module docstring) --
    # explicit drops are required for downgrade() to be a true inverse of upgrade().
    _csv_statement_status.drop(bind, checkfirst=True)
    _usage_event_outcome.drop(bind, checkfirst=True)
    _install_identity_type.drop(bind, checkfirst=True)
